In [ ]:
# Numpy -
import numpy as np
my_array=np.array([2,4,6,8,10],int) # 1D Array
print(my_array)
print(type(my_array))
print("Dimension ->",my_array.ndim)

[ 2  4  6  8 10]
<class 'numpy.ndarray'>
Dimension -> 1


In [ ]:
# 2D Array -
arr_2d=np.array([[4,8,10],[12,14,16],[20,22,24]])
print("2D Array ->\n",arr_2d)
print("Dimension ->",arr_2d.ndim)

2D Array ->
 [[ 4  8 10]
 [12 14 16]
 [20 22 24]]
Dimension -> 2


In [ ]:
# Zeros Array -
zero_array=np.zeros((2,3),int)
print("Zero Array ->\n",zero_array)


Zero Array ->
 [[0 0 0]
 [0 0 0]]


### 1D Zero Array

You can create a 1D array filled with zeros using `np.zeros()`. You just need to specify the desired size (number of elements) of the array.

In [ ]:
import numpy as np

one_d_zero_array = np.zeros(5, dtype=int) # Create a 1D array of 5 zeros
print("1D Zero Array ->", one_d_zero_array)
print("Dimension ->", one_d_zero_array.ndim)

1D Zero Array -> [0 0 0 0 0]
Dimension -> 1


In [ ]:
# 3D Array -
arr_3d=np.array([[[10,20,30],[40,50,60]],[[100,200,300],[400,500,600]]])
print("3D Array -> \n",arr_3d)
print("Dimension -> ",arr_3d.ndim)
print("Shape -> ",arr_3d.shape)

3D Array -> 
 [[[ 10  20  30]
  [ 40  50  60]]

 [[100 200 300]
  [400 500 600]]]
Dimension ->  3
Shape ->  (2, 2, 3)


In [ ]:
# Create an array using arange() function -
range_array=np.arange(0,10,2) # Start=0, Stop=10, Step=2)
print("Range Array -> \n",range_array)

Range Array -> 
 [0 2 4 6 8]


In [ ]:
# Linear Space Array - Array with evenly spaced values.
linspace_array=np.linspace(0,10,5) # Start=0,End=10,5 Points
print("Liner_Space Array ->\n",linspace_array)

Liner_Space Array ->
 [ 0.   2.5  5.   7.5 10. ]


In [ ]:
import numpy as np
# Random values from uniform distribution (0,1)
random_array=np.random.rand(2,3) # 2 Means 2 Rows, 3 Means 3 Columns
print("Random Array ->\n",random_array)
# Random values of uniform distribution from 10 and 20.
rand_uniform=np.random.uniform(10,15,(3,3))
print("Random Uniform Array ->\n",rand_uniform)

Random Array ->
 [[0.55853627 0.8296303  0.70575137]
 [0.14773155 0.97062661 0.76917162]]
Random Uniform Array ->
 [[10.62509083 10.07014771 12.71626658]
 [14.42613085 13.04756284 11.96312848]
 [11.38579657 14.74588001 12.83910602]]


In [ ]:
# Sample Array - Array operation
import numpy as np
sample_array=np.array([[20,45,65],[10,15,25]])
print("Sample Array ->\n",sample_array)
print("Shape ->",sample_array.shape)
print("Size ->",sample_array.size)
print("Data Type ->",sample_array.dtype)
print("Dimension ->",sample_array.ndim)

Sample Array ->
 [[20 45 65]
 [10 15 25]]
Shape -> (2, 3)
Size -> 6
Data Type -> int64
Dimension -> 2


# **Part 2: Indexing and Slicing**

In [ ]:
# Indexing and Slicing - 1D Array
import numpy as np
my_array=np.array([10,20,30,35,40,45,50,52])
print("Array ->\n",my_array)
print("First Element ->",my_array[0]) # Indexing
print("Range of Index ->\n",my_array[1:5])


Array ->
 [10 20 30 35 40 45 50 52]
First Element -> 10
Range of Index ->
 [20 30 35 40]


In [ ]:
# Indexing & Slicing - 2D Array -
import numpy as np
arr_2d=np.array([[5,10,15,20,25],[10,20,30,40,50],[40,45,68,30,32]])
print("2D Array ->\n",arr_2d)
print("Indexing ->",arr_2d[1,2]) # Access element at Row-1,Column-2
print("Slicing ->\n",arr_2d[0:2,1:3]) # Row Slicier,Column Slicier

2D Array ->
 [[ 5 10 15 20 25]
 [10 20 30 40 50]
 [40 45 68 30 32]]
Indexing -> 30
Slicing ->
 [[10 15]
 [20 30]]


In [ ]:
# Indexing & Slicing - 3D Array -
arr_3d=np.array([[[5,10,15,20,25],[10,20,30,40,50]],[[7,14,21,28,35],[8,16,24,32,40]]])
print("3D Array ->\n",arr_3d)
print("Indexing ->",arr_3d[0,1,3]) # Page,Row,Column

3D Array ->
 [[[ 5 10 15 20 25]
  [10 20 30 40 50]]

 [[ 7 14 21 28 35]
  [ 8 16 24 32 40]]]
Indexing -> 40


# **Boolean Indexing** -

In [ ]:
# Boolean Indexing -
my_arr=np.array([5,10,15,20,25])
print("Original Array ->\n",my_arr)
# Check each element of my_arr greater than 15
arr_bool=my_arr>15
print("Boolean Array ->\n",arr_bool)
# Unmask all values from the boolean array -
print("Filtered Elements ->\n",my_arr[arr_bool])
# Direct boolean indexing -
print("Even Numbers ->\n",my_arr[my_arr%2==0])


Original Array ->
 [ 5 10 15 20 25]
Boolean Array ->
 [False False False  True  True]
Filtered Elements ->
 [20 25]
Even Numbers ->
 [10 20]


## **Part 3: Reshape,Flatten,Ravel - Difference between copy and view**

In [ ]:
import numpy as np
my_arr=np.arange(1,13)
print("Main Array ->\n",my_arr)
reshape_arr=my_arr.reshape((3,4))
print("Reshapped Array ->\n",reshape_arr)
# flatten() - create a copy of the main array as 1D
flat_arr=reshape_arr.flatten()
print("Flattened Array ->\n",flat_arr)
# ravel() - create a view(if possible) of the main array as 1D
ravel_arr=reshape_arr.ravel()
print("Ravel Array ->\n",ravel_arr)
# Modify both array's
ravel_arr[0]=100
print("Modified Ravel Array ->\n",ravel_arr)
print("Original Array ->\n",reshape_arr)
flat_arr[1]=200
print("Modified Flattened Array ->\n",flat_arr)
print("Original Array ->\n",reshape_arr)

Main Array ->
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshapped Array ->
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened Array ->
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel Array ->
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Modified Ravel Array ->
 [100   2   3   4   5   6   7   8   9  10  11  12]
Original Array ->
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Modified Flattened Array ->
 [  1 200   3   4   5   6   7   8   9  10  11  12]
Original Array ->
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


# **Part 4: Stacking and Splitting**

In [ ]:
# Stacking -
import numpy as np
arr_1=np.array([[5,10,15,20,25],[10,20,30,40,50]])
arr_2=np.array([[7,14,21,28,35],[12,24,36,48,60]])
print("1st Array ->\n",arr_1)
print("2nd Array ->\n",arr_2)
# Horizontal Stacking (hstack())
h_stacked=np.hstack((arr_1,arr_2)) # Join side by side
print("Horizontal Stacked Array ->\n",h_stacked)
# Vertical Stacking (vstack())
v_stacked=np.vstack((arr_1,arr_2)) # Join vertically
print("Vertical Stacked Array ->\n",v_stacked)

1st Array ->
 [[ 5 10 15 20 25]
 [10 20 30 40 50]]
2nd Array ->
 [[ 7 14 21 28 35]
 [12 24 36 48 60]]
Horizontal Stacked Array ->
 [[ 5 10 15 20 25  7 14 21 28 35]
 [10 20 30 40 50 12 24 36 48 60]]
Vertical Stacked Array ->
 [[ 5 10 15 20 25]
 [10 20 30 40 50]
 [ 7 14 21 28 35]
 [12 24 36 48 60]]


In [ ]:
# Depth Stack -
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[10,20,30],[40,50,60]])
print("1st Array ->\n",a)
print("2nd Array ->\n",b)
d_stacked=np.dstack((a,b)) # Join page by page
print("Depth Stacked Array ->\n",d_stacked)

1st Array ->
 [[1 2 3]
 [4 5 6]]
2nd Array ->
 [[10 20 30]
 [40 50 60]]
Depth Stacked Array ->
 [[[ 1 10]
  [ 2 20]
  [ 3 30]]

 [[ 4 40]
  [ 5 50]
  [ 6 60]]]


In [ ]:
# Splitting -
my_arr=np.arange(1,13)
print("Array ->\n",my_arr)
split_arr=np.split(my_arr,3) # Split the array in 3 parts
print("Splitted Array ->\n",split_arr)

Array ->
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Splitted Array ->
 [array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]


In [ ]:
import numpy as np

# Assuming split_arr is the array that was previously split
# If not, you can create a sample split array for demonstration
# For this example, we'll use the 'split_arr' from the previous execution results.

# The split_arr is a list of arrays:
# print(split_arr)

joined_array = np.concatenate(split_arr)
print("Joined Array ->\n", joined_array)

Joined Array ->
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


# **Part 5: Search,Sort, and Filter of Numpy**

In [2]:
import numpy as np
new_arr=np.array([10,20,30,40,50])
print("Array ->\n",new_arr)
# Searching -
index=np.where(new_arr==30)
print("Index where 30 is present ->",index)
indices=np.where(new_arr>30)
print("Indices where values are greater than 30 ->",indices)

Array ->
 [10 20 30 40 50]
Index where 30 is present -> (array([2]),)
Indices where values are greater than 30 -> (array([3, 4]),)


In [4]:
# Sorting -
my_arr=np.array([60,50,30,40,10,20])
print("Array Before Sorting ->\n",my_arr)
sort_arr=np.sort(my_arr)
print("Array After Sorting ->\n",sort_arr)
sort_desc=np.sort(my_arr)[::-1]
print("Sorted Array (descending) ->\n",sort_desc)

Array Before Sorting ->
 [60 50 30 40 10 20]
Array After Sorting ->
 [10 20 30 40 50 60]
Sorted Array (descending) ->
 [60 50 40 30 20 10]


In [5]:
# Filter in numpy -
my_arr=np.array([5,10,15,20,25,30])
print("Array ->\n",my_arr)
even_arr=my_arr[my_arr%2==0]
print("Filtered Array(Even Numbers) ->\n",even_arr)


Array ->
 [ 5 10 15 20 25 30]
Filtered Array(Even Numbers) ->
 [10 20 30]
